"use client";

import { useState } from "react";
import { CheckCircle2, Send } from "lucide-react";
import { Eyebrow, Notice } from "@/components/Ui";

export default function FeedbackPage() {
  const [sent, setSent] = useState(false);
  return <div className="shell page-shell feedback-page"><div className="page-header"><Eyebrow>Correcciones y feedback</Eyebrow><h1 className="page-title">Ayúdanos a encontrar una regla mal interpretada.</h1><p className="page-intro">No incluyas salario, discapacidad, prestaciones, DNI ni otros datos personales. Describe la regla, fuente o barrera de acceso.</p></div><div className="feedback-grid"><form className="content-card content-card-padding form-card" onSubmit={(event) => { event.preventDefault(); setSent(true); }}><div className="field"><label htmlFor="feedback-type">Tipo</label><select id="feedback-type"><option>Error de política o cálculo</option><option>Fuente desactualizada</option><option>Problema de accesibilidad</option><option>Problema de privacidad o seguridad</option><option>Otro comentario</option></select></div><div className="field"><label htmlFor="feedback-reference">Referencia pública (opcional)</label><input id="feedback-reference" type="url" placeholder="https://…" /></div><div className="field"><label htmlFor="feedback-message">Descripción sin datos personales</label><textarea id="feedback-message" required minLength={20} rows={7} placeholder="Qué esperabas, qué observaste y qué fuente lo respalda…" /></div><label className="check-control"><input required type="checkbox" /><span>Confirmo que no he incluido datos fiscales o personales.</span></label><button className="button" type="submit"><Send size={17} aria-hidden="true" /> Preparar reporte local</button>{sent ? <Notice tone="success" title="Reporte preparado"><CheckCircle2 size={17} aria-hidden="true" /> Esta demo no envía mensajes externos. Copia el texto y abre una incidencia en el repositorio público cuando esté disponible.</Notice> : null}</form><aside><Notice tone="privacy" title="Canal sin datos fiscales">Los reportes son para reglas, fuentes y experiencia de uso. Nunca necesitamos tu caso real para registrar una corrección.</Notice></aside></div></div>;
}
