import type { Metadata } from "next";
import { GovernancePage } from "@/components/GovernancePage";
import { StatusBadge } from "@/components/Ui";

export const metadata: Metadata = { title: "Actualizaciones" };

export default function UpdatesPage() {
  return <GovernancePage eyebrow="Historial público" title="Cambios que dejan rastro." intro="Cada versión coordina aplicación, modelo, registro de políticas, datos y geografía."><div className="update-entry"><div><time dateTime="2026-07-13">13 julio 2026</time><StatusBadge tone="demo">0.1.0 PRE-LANZAMIENTO</StatusBadge></div><h2>Primera versión vertical</h2><ul><li>Calculadora multi-persona y comparación de tres escenarios.</li><li>API fiscal Python detrás de un Worker del mismo origen y contingencia edge identificada.</li><li>Registro de políticas y fuentes fechado.</li><li>Explorador territorial con datos sintéticos y controles de divulgación.</li><li>Manifiesto combinatorio del motor Python de 61.980.085.440 estados.</li><li>Estudio reproducible del motor Python: 2.000.000 hogares y 6.000.000 evaluaciones exactas.</li><li>Laboratorio fiscal nacional: IRPF por tramos, ahorro, carburantes, juego, loterías, patrimonio y partidas de gasto ajustables por Estado y comunidad, con impacto por renta, familia y edad.</li><li>Mapa SVG interactivo con límites oficiales generalizados (NUTS-2 2024, © EuroGeographics).</li><li>Estudio nacional de doble motor con nueve familias de barridos exhaustivos y recuento auditable de aplicaciones de parámetro-caso.</li><li>Paquetes de gobierno comparables con fichas homogéneas: trayectorias documentadas (BOE) y arquetipos sintéticos, sin logotipos ni recomendación.</li><li>Reto de equilibrio presupuestario y tarjeta-resumen PNG generada en el navegador.</li><li>Consulta por perfil de hogar aproximado, comparador de paquetes, modo directo para debates, widget embebible para medios y páginas por comunidad.</li><li>Documentación de privacidad, seguridad, validación y operaciones.</li></ul></div><h2>Próximo hito</h2><p>Validación fiscal de cada comunidad, hogares dorados contra Renta Web Open, calibración agregada alineada y sustitución de los datos DEMO por fuentes oficiales licenciadas.</p></GovernancePage>;
}
