/**
 * Revenue instruments of the national laboratory beyond IRPF. Baseline
 * revenue figures are rounded, reviewed public aggregates (AEAT annual
 * collection report 2024; regional ceded-tax statistics 2023) and are always
 * presented as an approximate reference, never as official liquidations.
 * Incidence profiles are stylised household-survey (EPF/ECV) patterns.
 */
import { consumptionWeights, gdpWeights, populationWeights } from "./demography";
import type {
  CommunityCode,
  IncidenceProfile,
  InstrumentDefinition,
} from "./types";

function normalise(values: number[]): number[] {
  const total = values.reduce((sum, value) => sum + value, 0);
  return values.map((value) => value / total);
}

function incidence(
  deciles: number[],
  familyTypes: number[],
  ageBands: number[],
): IncidenceProfile {
  return {
    deciles: normalise(deciles),
    familyTypes: normalise(familyTypes),
    ageBands: normalise(ageBands),
  };
}

/** Family-type incidence shorthand: [uni, pareja, pareja+hijos, mono, otros]. */
const FAMILY_CONSUMPTION = [18, 22, 34, 10, 16];
const FAMILY_INCOME_TAX = [16, 24, 38, 8, 14];

/** Age-band incidence shorthand: [<30, 30-44, 45-64, 65+]. */
const AGE_CONSUMPTION = [7, 27, 41, 25];
const AGE_WORKING = [8, 32, 48, 12];
const AGE_FLAT = [5.5, 24, 39, 31.5];

const consumption = consumptionWeights();
const population = populationWeights();
const gdp = gdpWeights();

function scaledWeights(
  base: Record<CommunityCode, number>,
  overrides: Partial<Record<CommunityCode, number>> = {},
): Record<CommunityCode, number> {
  const merged = { ...base, ...overrides } as Record<CommunityCode, number>;
  const total = Object.values(merged).reduce((sum, value) => sum + value, 0);
  return Object.fromEntries(
    Object.entries(merged).map(([code, value]) => [code, value / total]),
  ) as Record<CommunityCode, number>;
}

/** Corporate-tax delegation weights: strongly concentrated in headquarters. */
const CORPORATE_WEIGHTS = scaledWeights(gdp, {
  "13": 0.44,
  "09": 0.17,
  "01": 0.06,
  "10": 0.05,
  "16": 0.055,
  "15": 0.012,
});

/** Fuel consumption weights: population adjusted by rural/transit intensity. */
const FUEL_WEIGHTS = scaledWeights(population, {
  "07": 0.062,
  "08": 0.058,
  "02": 0.038,
  "11": 0.028,
  "12": 0.062,
  "13": 0.125,
  "09": 0.155,
});

/** Housing-transfer (ITP) weights: transaction markets, coastal and urban. */
const ITP_WEIGHTS = scaledWeights(consumption, {
  "01": 0.17,
  "04": 0.055,
  "05": 0.05,
  "09": 0.19,
  "10": 0.14,
  "13": 0.16,
});

/** Wealth-tax weights: taxable declared wealth is Catalonia-heavy because of
 * the Madrid regional full rebate in the baseline. */
const WEALTH_WEIGHTS = scaledWeights(gdp, {
  "09": 0.42,
  "10": 0.13,
  "01": 0.08,
  "13": 0.02,
  "16": 0.03,
  "15": 0.012,
});

export const INSTRUMENTS: InstrumentDefinition[] = [
  {
    id: "iva_general",
    name: "IVA — tipo general",
    shortName: "IVA 21 %",
    group: "consumo",
    baselineRate: 21,
    rateUnit: "percent",
    minRate: 10,
    maxRate: 30,
    step: 0.5,
    baselineRevenueMEur: 66_500,
    attribution: { kind: "state", cededShare: 0.5 },
    regionalWeights: consumption,
    baseElasticity: -0.2,
    incidence: incidence(
      [4.5, 5.5, 6.5, 7.5, 8.5, 9.5, 10.5, 12, 14.5, 21],
      FAMILY_CONSUMPTION,
      AGE_CONSUMPTION,
    ),
    regionallyAdjustable: false,
    excludedCommunities: ["05", "18", "19"],
    sourceNote: "AEAT 2024: IVA total ≈ 90.500 M€; el tipo general aporta ≈ 73 %.",
  },
  {
    id: "iva_reducido",
    name: "IVA — tipo reducido",
    shortName: "IVA 10 %",
    group: "consumo",
    baselineRate: 10,
    rateUnit: "percent",
    minRate: 4,
    maxRate: 21,
    step: 0.5,
    baselineRevenueMEur: 19_000,
    attribution: { kind: "state", cededShare: 0.5 },
    regionalWeights: consumption,
    baseElasticity: -0.15,
    incidence: incidence(
      [6, 7, 7.5, 8, 9, 9.5, 10.5, 12, 13.5, 17],
      FAMILY_CONSUMPTION,
      AGE_CONSUMPTION,
    ),
    regionallyAdjustable: false,
    excludedCommunities: ["05", "18", "19"],
    sourceNote: "AEAT 2024; hostelería, transporte y vivienda concentran el tipo reducido.",
  },
  {
    id: "iva_superreducido",
    name: "IVA — tipo superreducido",
    shortName: "IVA 4 %",
    group: "consumo",
    baselineRate: 4,
    rateUnit: "percent",
    minRate: 0,
    maxRate: 10,
    step: 0.5,
    baselineRevenueMEur: 5_000,
    attribution: { kind: "state", cededShare: 0.5 },
    regionalWeights: consumption,
    baseElasticity: -0.05,
    incidence: incidence(
      [10, 10.5, 10.5, 10.5, 10, 10, 9.5, 9.5, 9.5, 10],
      [20, 21, 33, 12, 14],
      [6, 25, 37, 32],
    ),
    regionallyAdjustable: false,
    excludedCommunities: ["05", "18", "19"],
    sourceNote: "Alimentos básicos y medicamentos; incidencia proporcionalmente mayor en rentas bajas.",
  },
  {
    id: "igic",
    name: "IGIC (Canarias) — tipo general",
    shortName: "IGIC 7 %",
    group: "consumo",
    baselineRate: 7,
    rateUnit: "percent",
    minRate: 0,
    maxRate: 15,
    step: 0.5,
    baselineRevenueMEur: 2_600,
    attribution: { kind: "regional", cededShare: 1 },
    regionalWeights: scaledWeights(
      Object.fromEntries(
        Object.keys(population).map((code) => [code, code === "05" ? 1 : 0]),
      ) as Record<CommunityCode, number>,
    ),
    baseElasticity: -0.2,
    incidence: incidence(
      [5, 6, 7, 8, 8.5, 9.5, 10.5, 12, 14, 19.5],
      FAMILY_CONSUMPTION,
      AGE_CONSUMPTION,
    ),
    regionallyAdjustable: false,
    sourceNote: "Recaudación IGIC ≈ 2.600 M€ (Gobierno de Canarias, 2024).",
  },
  {
    id: "sociedades",
    name: "Impuesto sobre Sociedades — tipo general",
    shortName: "Sociedades 25 %",
    group: "empresas",
    baselineRate: 25,
    rateUnit: "percent",
    minRate: 10,
    maxRate: 40,
    step: 0.5,
    baselineRevenueMEur: 39_100,
    attribution: { kind: "state", cededShare: 0 },
    regionalWeights: CORPORATE_WEIGHTS,
    baseElasticity: -0.25,
    incidence: incidence(
      [1.5, 2, 2.5, 3, 4, 5, 6, 8, 15, 53],
      [22, 26, 28, 6, 18],
      [6, 26, 44, 24],
    ),
    householdBorneShare: 0.7,
    regionallyAdjustable: false,
    sourceNote:
      "AEAT 2024 ≈ 39.100 M€. La distribución territorial refleja domicilio fiscal, no actividad.",
  },
  {
    id: "hidrocarburos_gasolina",
    name: "Hidrocarburos — gasolina (tipo estatal)",
    shortName: "Gasolina €/1.000 l",
    group: "especiales",
    baselineRate: 472.69,
    rateUnit: "eurosPerUnit",
    unitLabel: "€/1.000 litros",
    minRate: 200,
    maxRate: 800,
    step: 5,
    baselineRevenueMEur: 3_700,
    attribution: { kind: "state", cededShare: 0.58 },
    regionalWeights: FUEL_WEIGHTS,
    baseElasticity: -0.3,
    incidence: incidence(
      [3, 4.5, 6, 7.5, 9, 10, 11.5, 13, 15, 20.5],
      [14, 22, 40, 9, 15],
      [9, 33, 44, 14],
    ),
    regionallyAdjustable: false,
    sourceNote: "Ley 38/1992; recaudación total hidrocarburos ≈ 12.300 M€ (AEAT 2024).",
  },
  {
    id: "hidrocarburos_diesel",
    name: "Hidrocarburos — gasóleo (tipo estatal)",
    shortName: "Diésel €/1.000 l",
    group: "especiales",
    baselineRate: 379,
    rateUnit: "eurosPerUnit",
    unitLabel: "€/1.000 litros",
    minRate: 200,
    maxRate: 800,
    step: 5,
    baselineRevenueMEur: 8_600,
    attribution: { kind: "state", cededShare: 0.58 },
    regionalWeights: FUEL_WEIGHTS,
    baseElasticity: -0.25,
    incidence: incidence(
      [3.5, 5, 6.5, 8, 9.5, 10.5, 11.5, 13, 14.5, 18],
      [13, 22, 41, 9, 15],
      [8, 33, 46, 13],
    ),
    regionallyAdjustable: false,
    sourceNote: "Incluye gasóleo A y resto de productos; profesionales con devolución parcial.",
  },
  {
    id: "tabaco",
    name: "Labores del tabaco",
    shortName: "Tabaco",
    group: "especiales",
    baselineRate: 51,
    rateUnit: "percent",
    minRate: 30,
    maxRate: 75,
    step: 0.5,
    baselineRevenueMEur: 6_700,
    attribution: { kind: "state", cededShare: 0.58 },
    regionalWeights: scaledWeights(population, { "01": 0.2, "10": 0.125 }),
    baseElasticity: -0.45,
    incidence: incidence(
      [9, 10, 10.5, 11, 10.5, 10, 10, 10, 9.5, 9.5],
      [28, 22, 26, 12, 12],
      [8, 30, 45, 17],
    ),
    regionallyAdjustable: false,
    sourceNote: "Tipo proporcional sobre PVP más específico; modelado como carga media conjunta.",
  },
  {
    id: "alcohol",
    name: "Alcohol, cerveza y productos intermedios",
    shortName: "Alcohol",
    group: "especiales",
    baselineRate: 100,
    rateUnit: "percent",
    minRate: 50,
    maxRate: 250,
    step: 5,
    baselineRevenueMEur: 1_270,
    attribution: { kind: "state", cededShare: 0.58 },
    regionalWeights: consumption,
    baseElasticity: -0.4,
    incidence: incidence(
      [6, 7, 8, 9, 9.5, 10, 10.5, 11, 12, 17],
      [26, 24, 26, 9, 15],
      [12, 30, 40, 18],
    ),
    regionallyAdjustable: false,
    sourceNote: "Índice 100 = tipos vigentes de la Ley 38/1992 (alcohol, cerveza e intermedios).",
  },
  {
    id: "electricidad",
    name: "Impuesto especial sobre la electricidad",
    shortName: "Electricidad",
    group: "especiales",
    baselineRate: 5.11,
    rateUnit: "percent",
    minRate: 0.5,
    maxRate: 10,
    step: 0.1,
    baselineRevenueMEur: 1_400,
    attribution: { kind: "state", cededShare: 1 },
    regionalWeights: consumption,
    baseElasticity: -0.1,
    incidence: incidence(
      [6, 7, 7.5, 8, 9, 9.5, 10.5, 11.5, 13.5, 17.5],
      [22, 22, 32, 10, 14],
      AGE_FLAT,
    ),
    regionallyAdjustable: false,
    sourceNote: "Tipo restablecido al 5,11 % desde 2024; totalmente cedido a las CCAA.",
  },
  {
    id: "primas_seguros",
    name: "Impuesto sobre primas de seguros",
    shortName: "Seguros 8 %",
    group: "consumo",
    baselineRate: 8,
    rateUnit: "percent",
    minRate: 0,
    maxRate: 15,
    step: 0.5,
    baselineRevenueMEur: 2_900,
    attribution: { kind: "state", cededShare: 0 },
    regionalWeights: consumption,
    baseElasticity: -0.15,
    incidence: incidence(
      [4, 5, 6, 7.5, 8.5, 9.5, 11, 12.5, 15, 21],
      [16, 24, 38, 8, 14],
      [7, 29, 44, 20],
    ),
    regionallyAdjustable: false,
    sourceNote: "Tipo del 8 % desde 2021; AEAT 2024 ≈ 2.900 M€.",
  },
  {
    id: "matriculacion",
    name: "Impuesto de matriculación",
    shortName: "Matriculación",
    group: "especiales",
    baselineRate: 100,
    rateUnit: "percent",
    minRate: 0,
    maxRate: 300,
    step: 5,
    baselineRevenueMEur: 700,
    attribution: { kind: "state", cededShare: 1 },
    regionalWeights: consumption,
    baseElasticity: -0.5,
    incidence: incidence(
      [2, 3, 4, 5.5, 7, 9, 11, 13.5, 17, 28],
      [14, 26, 38, 7, 15],
      [8, 32, 44, 16],
    ),
    regionallyAdjustable: false,
    sourceNote: "Índice 100 = escala vigente por emisiones; totalmente cedido.",
  },
  {
    id: "plasticos",
    name: "Impuesto a envases de plástico no reutilizable",
    shortName: "Plásticos",
    group: "especiales",
    baselineRate: 0.45,
    rateUnit: "eurosPerUnit",
    unitLabel: "€/kg",
    minRate: 0,
    maxRate: 2,
    step: 0.05,
    baselineRevenueMEur: 600,
    attribution: { kind: "state", cededShare: 0 },
    regionalWeights: consumption,
    baseElasticity: -0.3,
    incidence: incidence(
      [8, 9, 9.5, 10, 10, 10, 10, 10.5, 11, 12],
      FAMILY_CONSUMPTION,
      AGE_CONSUMPTION,
    ),
    householdBorneShare: 0.9,
    regionallyAdjustable: false,
    sourceNote: "Ley 7/2022; 0,45 €/kg; AEAT 2024 ≈ 600 M€.",
  },
  {
    id: "juego_online",
    name: "Actividades de juego online (estatal)",
    shortName: "Juego online 20 %",
    group: "juego",
    baselineRate: 20,
    rateUnit: "percent",
    minRate: 5,
    maxRate: 50,
    step: 1,
    baselineRevenueMEur: 380,
    attribution: { kind: "state", cededShare: 0 },
    regionalWeights: scaledWeights(population, { "01": 0.2, "13": 0.17, "10": 0.12 }),
    baseElasticity: -0.6,
    incidence: incidence(
      [8, 9, 10, 10.5, 10.5, 10.5, 10.5, 10, 10.5, 10],
      [34, 20, 22, 10, 14],
      [22, 36, 32, 10],
    ),
    regionallyAdjustable: false,
    sourceNote: "20 % sobre GGR (Ley 13/2011); alta sustitución hacia juego no regulado.",
  },
  {
    id: "juego_presencial",
    name: "Tributos sobre el juego presencial (autonómicos)",
    shortName: "Juego presencial",
    group: "juego",
    baselineRate: 100,
    rateUnit: "percent",
    minRate: 0,
    maxRate: 300,
    step: 5,
    baselineRevenueMEur: 1_700,
    attribution: { kind: "regional", cededShare: 1 },
    regionalWeights: scaledWeights(consumption, { "01": 0.18, "13": 0.16, "10": 0.12 }),
    baseElasticity: -0.5,
    incidence: incidence(
      [8, 9.5, 10, 10.5, 10.5, 10.5, 10.5, 10, 10, 10.5],
      [30, 24, 20, 10, 16],
      [10, 26, 40, 24],
    ),
    regionallyAdjustable: true,
    sourceNote: "Índice 100 = tasas vigentes sobre casinos, bingos y máquinas por CCAA.",
  },
  {
    id: "loterias",
    name: "Gravamen especial sobre premios de loterías",
    shortName: "Loterías 20 %",
    group: "juego",
    baselineRate: 20,
    rateUnit: "percent",
    minRate: 0,
    maxRate: 50,
    step: 1,
    baselineRevenueMEur: 600,
    attribution: { kind: "state", cededShare: 0 },
    regionalWeights: population,
    baseElasticity: -0.3,
    incidence: incidence(
      [9, 10, 10.5, 10.5, 10.5, 10.5, 10, 10, 9.5, 9.5],
      [26, 25, 25, 10, 14],
      [6, 22, 40, 32],
    ),
    regionallyAdjustable: false,
    sourceNote: "20 % sobre premios > 40.000 € (SELAE, ONCE y Cruz Roja).",
  },
  {
    id: "patrimonio",
    name: "Impuesto sobre el patrimonio (autonómico)",
    shortName: "Patrimonio",
    group: "patrimonio",
    baselineRate: 100,
    rateUnit: "percent",
    minRate: 0,
    maxRate: 300,
    step: 5,
    baselineRevenueMEur: 1_400,
    attribution: { kind: "regional", cededShare: 1 },
    regionalWeights: WEALTH_WEIGHTS,
    baseElasticity: -0.35,
    incidence: incidence(
      [0, 0, 0, 0, 0, 0, 0.5, 1.5, 8, 90],
      [22, 34, 24, 4, 16],
      [2, 12, 40, 46],
    ),
    regionallyAdjustable: true,
    sourceNote:
      "Índice 100 = escalas y bonificaciones vigentes por CCAA (Madrid bonifica el 100 %).",
  },
  {
    id: "grandes_fortunas",
    name: "Impuesto de solidaridad de grandes fortunas",
    shortName: "Grandes fortunas",
    group: "patrimonio",
    baselineRate: 100,
    rateUnit: "percent",
    minRate: 0,
    maxRate: 300,
    step: 5,
    baselineRevenueMEur: 600,
    attribution: { kind: "state", cededShare: 0 },
    regionalWeights: scaledWeights(gdp, { "13": 0.62, "01": 0.12 }),
    baseElasticity: -0.35,
    incidence: incidence(
      [0, 0, 0, 0, 0, 0, 0, 0.5, 3.5, 96],
      [22, 36, 22, 2, 18],
      [1, 10, 42, 47],
    ),
    regionallyAdjustable: false,
    sourceNote: "Patrimonios > 3 M€ no gravados por patrimonio autonómico (Madrid concentra la base).",
  },
  {
    id: "sucesiones",
    name: "Sucesiones y donaciones (autonómico)",
    shortName: "Sucesiones",
    group: "patrimonio",
    baselineRate: 100,
    rateUnit: "percent",
    minRate: 0,
    maxRate: 300,
    step: 5,
    baselineRevenueMEur: 3_600,
    attribution: { kind: "regional", cededShare: 1 },
    regionalWeights: scaledWeights(gdp, { "09": 0.22, "13": 0.14 }),
    baseElasticity: -0.25,
    incidence: incidence(
      [0.5, 1, 2, 3, 4, 6, 8, 12, 21, 42.5],
      [24, 30, 24, 6, 16],
      [4, 16, 46, 34],
    ),
    regionallyAdjustable: true,
    sourceNote: "Índice 100 = tarifas y bonificaciones autonómicas vigentes (muy heterogéneas).",
  },
  {
    id: "itp_ajd",
    name: "Transmisiones patrimoniales y AJD (autonómico)",
    shortName: "ITP-AJD",
    group: "patrimonio",
    baselineRate: 100,
    rateUnit: "percent",
    minRate: 0,
    maxRate: 200,
    step: 5,
    baselineRevenueMEur: 13_500,
    attribution: { kind: "regional", cededShare: 1 },
    regionalWeights: ITP_WEIGHTS,
    baseElasticity: -0.3,
    incidence: incidence(
      [2, 3, 4.5, 6, 8, 9.5, 11.5, 14, 17.5, 24],
      [18, 26, 34, 8, 14],
      [12, 34, 36, 18],
    ),
    regionallyAdjustable: true,
    sourceNote: "Índice 100 = tipos vigentes por CCAA (6–11 % vivienda usada, AJD 0,5–1,5 %).",
  },
  {
    id: "irnr",
    name: "Impuesto sobre la renta de no residentes",
    shortName: "IRNR",
    group: "renta",
    baselineRate: 100,
    rateUnit: "percent",
    minRate: 50,
    maxRate: 200,
    step: 5,
    baselineRevenueMEur: 4_000,
    attribution: { kind: "state", cededShare: 0 },
    regionalWeights: scaledWeights(gdp, { "13": 0.35, "09": 0.2, "04": 0.07, "05": 0.06 }),
    baseElasticity: -0.4,
    incidence: incidence(
      [2, 2, 2, 3, 4, 6, 8, 11, 19, 43],
      [24, 28, 24, 6, 18],
      [6, 26, 44, 24],
    ),
    householdBorneShare: 0.3,
    regionallyAdjustable: false,
    sourceNote: "Índice 100 = tipos vigentes (19 %/24 %); carga soportada sobre todo por no residentes.",
  },
  {
    id: "transacciones_financieras",
    name: "Impuesto sobre transacciones financieras",
    shortName: "ITF 0,2 %",
    group: "empresas",
    baselineRate: 0.2,
    rateUnit: "percent",
    minRate: 0,
    maxRate: 1,
    step: 0.05,
    baselineRevenueMEur: 300,
    attribution: { kind: "state", cededShare: 0 },
    regionalWeights: scaledWeights(gdp, { "13": 0.5, "16": 0.09 }),
    baseElasticity: -0.7,
    incidence: incidence(
      [0.5, 1, 1.5, 2, 3, 4.5, 6.5, 9.5, 17, 54.5],
      [22, 30, 26, 4, 18],
      [4, 20, 44, 32],
    ),
    householdBorneShare: 0.6,
    regionallyAdjustable: false,
    sourceNote: "0,2 % sobre compras de acciones de grandes cotizadas (Ley 5/2020).",
  },
  {
    id: "servicios_digitales",
    name: "Impuesto sobre determinados servicios digitales",
    shortName: "IDSD 3 %",
    group: "empresas",
    baselineRate: 3,
    rateUnit: "percent",
    minRate: 0,
    maxRate: 10,
    step: 0.5,
    baselineRevenueMEur: 300,
    attribution: { kind: "state", cededShare: 0 },
    regionalWeights: consumption,
    baseElasticity: -0.4,
    incidence: incidence(
      [5, 6, 7, 8, 9, 10, 11, 12, 14, 18],
      [24, 24, 30, 8, 14],
      [14, 34, 36, 16],
    ),
    householdBorneShare: 0.8,
    regionallyAdjustable: false,
    sourceNote: "3 % sobre publicidad e intermediación digital (Ley 4/2020).",
  },
  {
    id: "cotizaciones",
    name: "Cotizaciones sociales (tipo total equivalente)",
    shortName: "Cotizaciones",
    group: "cotizaciones",
    baselineRate: 36.5,
    rateUnit: "percent",
    minRate: 25,
    maxRate: 45,
    step: 0.25,
    baselineRevenueMEur: 152_900,
    attribution: { kind: "state", cededShare: 0 },
    regionalWeights: scaledWeights(gdp, {}),
    baseElasticity: -0.15,
    incidence: incidence(
      [1.5, 3, 5, 6.5, 8.5, 10, 11.5, 13.5, 16.5, 24],
      FAMILY_INCOME_TAX,
      AGE_WORKING,
    ),
    regionallyAdjustable: false,
    sourceNote:
      "Suma aproximada de tipos de empresa y persona trabajadora (contingencias, desempleo, MEI, FP y FOGASA) sobre la base 2026.",
  },
];

export const INSTRUMENT_BY_ID: ReadonlyMap<string, InstrumentDefinition> = new Map(
  INSTRUMENTS.map((instrument) => [instrument.id, instrument]),
);

export const INSTRUMENT_GROUP_LABELS: Record<InstrumentDefinition["group"], string> = {
  renta: "Renta",
  consumo: "Consumo",
  especiales: "Impuestos especiales",
  juego: "Juego y loterías",
  patrimonio: "Riqueza y transmisiones",
  empresas: "Empresas y capital",
  cotizaciones: "Cotizaciones sociales",
};
